apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: onfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ecr-access
      containers:
      - name: backend
        image: 365305373147.dkr.ecr.us-east-1.amazonaws.com/onfinance-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/weather?latitude=51.5&longitude=0
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10