apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: onfinance
type: Opaque
stringData:
  DB_USER: your_db_user
  DB_PASSWORD: your_db_password
  DB_HOST: your-db-host.rds.amazonaws.com
  DB_NAME: your_db_name
  AWS_REGION: us-east-1
  S3_BUCKET: weather-data-response