apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amazoncloudwatchagents.cloudwatch.aws.amazon.com
spec:
  group: cloudwatch.aws.amazon.com
  names:
    kind: AmazonCloudWatchAgent
    listKind: AmazonCloudWatchAgentList
    plural: amazoncloudwatchagents
    singular: amazoncloudwatchagent
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
